name: Build & Test (Laravel 9, 10)
env:
    TESTING_ENV: ${{ secrets.TESTING_ENV }}

on:
    pull_request:
        branches:
            - 'main'
        types: [ opened, synchronize, reopened, ready_for_review ]
    push:
        branches:
            - 'main'

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                version: [
                    '"laravel/framework" "^9" "orchestra/testbench" "^7" "phpunit/phpunit" "^9.5"',
                    '"laravel/framework" "^10" "orchestra/testbench" "^8"'
                ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                if: success()

            -   name: Setup PHP with coverage driver
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: pcov

            -   name: Setup
                if: success()
                run: |
                    sudo service mysql start
                    php -v
                    mysql -uroot -proot -e "CREATE DATABASE priority_queue;"
                    composer install --no-interaction
                    composer require ${{ matrix.version }} -W
                    echo "$TESTING_ENV" > .env.testing

            -   name: PHPUnit tests
                if: success() && github.event.pull_request.draft == false
                run: |
                    composer test
